### ISSUE TITLE
Toggle respect for .gitignore

### ISSUE THREAD

**Issue by johandebeurs** [alfredapp/ignore-in-alfred-workflow#10]
### Feature details

Respecting .gitignore is a handy feature of `fd` and it would be nice if there was support for this in Alfred's file search. There are drawbacks for doing it via this alfred-ignore tag approach, but suggesting it as a feature here in case @vitorgalvao you have smarter ideas than I on how to achieve this

**Comment by vitorgalvao** [comment]
That’s not related to the workflow, which ignores what you tell it to. Alfred’s search uses Spotlight’s indexing, which does not allow for negative searches. [Same thing as `node_modules`.](https://www.alfredapp.com/help/kb/node-modules/)

Furthermore, respecting `.gitignore` would make searches *significantly* slower because it’d have to transverse the parent of every file up to the root of the file system. Try doing an `fd` search of your whole hard drive and see how slow that is. `fd` doesn’t keep an index.

**Comment by johandebeurs** [comment]
An alternative suggestion then - how about a modifier key for recursive tagging of all items within a folder? That might help achieve the goal in a slightly different way

**Comment by vitorgalvao** [comment]
It already tags recursively. That’s the only behaviour.

**Comment by johandebeurs** [comment]
Apologies for the confusion then - not in my experience. I'll see if I can find out why its failing to do so from the logs

**Comment by johandebeurs** [comment]
No log errors appear, and I can replicate as-intended functionality on small directories, but for large directories (e.g., >100k files) it appears to tag the parent folder and then not complete any recursive tagging.  Is there a max program execution timeout / is there a threshold of directory size over which you don't recommended to go?

**Comment by vitorgalvao** [comment]
Are you sure the child files aren’t being tagged? Or are you assuming that’s the case because you can still find them? Do a Get Info on some to make sure, as you should be able to see the `alfred:ignore` tag at the top.

After files are tagged, Spotlight will have to reindex them to see that the tag was added, so if you’re doing that large of a number of files, I wouldn’t be surprised if it takes some time for the change to stick. You may need to wait a while.

It’s also possible that with so many files changing at once, either Spotlight or FS Events gives up, and which point you may need to e.g. for a Spotlight reindex.

Also, if you’re doing so many files I recommend you instead add the folder to System Preferences → Spotlight → Search Privacy. With tagging, you’re going to have to reapply it every time you add another file.

**Comment by johandebeurs** [comment]
Ack. 

Files aren't tagged, i.e., there is no tag added in the info window.  Command has been running for about an hour since I said I'd debug above--at least I assume so according to Alfred's debug window not yet printing a `Processing complete` message, and the number of tagged files is slowly increasing. At ~70k to date for a folder of ~330k files

Any recommended way of digging into progress/other debugging/killing the long running tasks?

On some other testing, running:
`tag -m "alfred:ignore" -R ~/dir/ignored/by/workflow | wc -l`
gives different results to
`ls -R ~/dir/ignored/by/workflow | wc -l`
Is this expected?

**Comment by vitorgalvao** [comment]
> at least I assume so according to Alfred's debug window not yet printing a `Processing complete` message

In this case it wouldn’t show it.

> Any recommended way of digging into progress/other debugging/killing the long running tasks?

Run `pgrep -f 'tag add'` in a terminal and you’ll get a process ID number if it’s still running. It won’t tell you the progress, though. You can `pkill -f 'tag add'` to stop it. You may also want to run the Universal Action to Stop Ignoring in Alfred to remove the tags.

> On some other testing, running:
> `tag -m "alfred:ignore" -R ~/dir/ignored/by/workflow | wc -l`
> gives different results to
> `ls -R ~/dir/ignored/by/workflow | wc -l`
> Is this expected?

You said that the number of tagged files is increasing, so that makes sense. Either way, I can’t attest to what *that* `tag` does or how it works. The `tag` that the Automation Task is running is bespoke code I wrote 100% of.
