### ISSUE TITLE
Folder doesn't get ignored

### ISSUE THREAD

**Issue by ab-qf** [alfredapp/ignore-in-alfred-workflow#2]
### Workflow version

v2022.3

### Alfred version

5.0.6[2110]

### macOS version

13.1

### Debugger output

```alfred_debugger
[11:07:23.120] Logging Started...
[11:07:32.008] Ignore in Alfred[File Filter] Processing complete
[11:07:32.013] Ignore in Alfred[File Filter] Passing output '/Users/abo/miniforge3' to Automation Task
[11:07:32.015] ERROR: Ignore in Alfred[Automation Task] Task not found 'com.alfredapp.automation.core/files-and-folders/path.tags.add'
```

### More details

Ignoring a folder does't work for me. I tried to ignore "miniforge3" folder, so all the Python packages don't show up in my searches any more, but it doesn't work.

I also tried manually tagging a folder "alfred:ignore" - which also didn't work. Folder and subitems still showed in Alfred search.

**Comment by vitorgalvao** [comment]
> [11:07:32.015] ERROR: Ignore in Alfred[Automation Task] Task not found 'com.alfredapp.automation.core/files-and-folders/path.tags.add'

You have to double-click the Automation Task object ([it will be showing in red](https://www.alfredapp.com/help/workflows/automations/automation-task/#colours)) and update.

> I also tried manually tagging a folder "alfred:ignore" - which also didn't work.

Because the folder is directly under your home and search optimises that. To change the behaviour go to Alfred Preferences → Features → Default Results and Reset the Search Scope to Applications and Home.

**Comment by ab-qf** [comment]
While I am not getting an immediate error in the debug windows anymore now, it still doesn't work as expected: I still get search results from the ignored folder and subfolders.

Also, an error appears around 2 minutes after the initial ignore workflow:

```[10:35:56.775] Ignore in Alfred[File Action] Processing complete
[10:35:56.776] Ignore in Alfred[File Action] Passing output '/Users/abo/miniforge3' to Automation Task
[10:35:56.776] Ignore in Alfred[Automation Task] Running task 'Add Tags' with arguments (
    "/Users/abo/miniforge3"
)
[10:37:02.323] ERROR: Ignore in Alfred[Automation Task] Task Error: Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSOSStatusErrorDomain Code=-8058 "(null)" UserInfo={NSURLKeysOfUnsetValuesKey=(
    NSURLTagNamesKey
)}```

**Comment by vitorgalvao** [comment]
Have you reset the search scope, as per the previous post?

**Comment by ab-qf** [comment]
Yes, I did reset it to Applications and Home as you advised.

**Comment by vitorgalvao** [comment]
Try the workflow on something not directly inside your home folder, like a folder in your Desktop (not the Desktop itself). Does that work?

But please reboot first. With that error you got (which no one has ever reported) something else might be amiss.

**Comment by ab-qf** [comment]
It does work perfectly for folders which are "level 2" from home folder, so $HOME/Documents/ViberDownloads for instance.

So, there is no chance to get it working for something like $HOME/miniforge3?

**Comment by vitorgalvao** [comment]
It should work with the correct scope. It probably didn’t due to the error you got. That should indicate that one of the children of the folder couldn’t be processed. Maybe it was removed while the process was going on, or it has strict access permissions? I’ve never used miniforge so I’m not intimately familiar with the directory structure.

Ideally the error would’ve shown exactly where it found a problem. Though that might be possible to figure out approximately by seeing which files and folders had the tag added. Presumably it wasn't added past a certain point.
