### ISSUE TITLE
Stop Ignoring Folders not appearing

### ISSUE THREAD

**Issue by NicholasSloan** [alfredapp/ignore-in-alfred-workflow#7]
<img width="297" alt="Screenshot of Path Finder (18-08-2023, 06-38-04)" src="https://github.com/alfredapp/ignore-in-alfred-workflow/assets/20109637/eed42435-fa6e-4561-8b88-335e5fc1380c">

I am finding that the two commands **Stop Ignoring in Alfred** and **Stop Ignoring Folders in Alfred** are showing up in the actions list with the same title (i.e. there is no **Stop Ignoring Folders in Alfred**. (Difficult to tell whether this affects behaviour since it is difficult to keep track of which command is being applied.)

V 2023.3, Alfred 5.1.2, Mac OS 12.6.7

Thanks for a brilliant workflow nevertheless!

**Comment by vitorgalvao** [comment]
You’re seeing a second result because you have on Alfred Preferences → Universal Actions → Actions → Workflow Script Filters (at the bottom). If you untick the checkbox you’ll only see one result.

But both of what you’re seeing will do the same thing, so you can use either.

> Thanks for a brilliant workflow nevertheless!

Thank you for the kind words!

**Comment by NicholasSloan** [comment]
Thanks Vitor, clear explanation.
I understand that Ignore/Stop ignoring… are the only two Universal Actions.

I am still puzzled about when Stop Ignoring Folders shows up: you show both under the search keyword unignore. If I type this I only ever see a file/folder list, I don't see any way of executing two different commands. What am I missing (again)?

I'm also puzzled by the icon: is it a cement mixer, a human cannon, or Pooh Bear without a head? Not a criticism, I like it, just puzzled!

**Comment by vitorgalvao** [comment]
> you show both under the search keyword unignore.

For folders the keyword is `unignore folder` (with the space between words). Everything (including folders) shows up with just `unignore` so you can use that one alone, the `folder` is just a convenience for more focused results.

> a human cannon

That! It’s a comical take on “shooting the results far away” (because “ignoring” is a bit of an abstract concept for a small icon). I quite like this one graphically and enjoy how the colours fit with my theme (in the screenshots).
